name: Hugo Site CI

on:
  push:
    branches:
      - main # Replace 'main' with your default branch name (e.g., master, develop)

permissions: # <--- 在這裡加入 permissions 區塊
  contents: read
  pages: write
  id-token: write # <--- 確保這行存在

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_ENV: production
      GIT_SUBMODULE_STRATEGY: recursive
      PUBLIC_DIR: public

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: ${{ env.GIT_SUBMODULE_STRATEGY }}

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest' # Or a specific version like '0.127.0'
          extended: true 

      - name: Build Hugo site for test (if not default branch)
        if: github.ref_name != github.event.repository.default_branch
        run: hugo --gc --minify

      - name: Deploy to GitHub Pages (if default branch)
        if: github.ref_name == github.event.repository.default_branch
        run: hugo --gc --minify
      - name: Upload production artifact
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PUBLIC_DIR }}

  # This job is required to deploy to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
